apiVersion: apps/v1
kind: Deployment
metadata:
  name: store1-frontend
  namespace: store1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store1-frontend
  template:
    metadata:
      labels:
        app: store1-frontend
    spec:
      containers:
        - name: frontend
          image: davidkhan/medusadev:frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: store1-secrets