apiVersion: apps/v1
kind: Deployment
metadata:
  name: store1-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store1-postgres
  template:
    metadata:
      labels:
        app: store1-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: medusa
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store1-secrets
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: store1-postgres
spec:
  selector:
    app: store1-postgres
  ports:
    - port: 5432
