apiVersion: v1
kind: Secret
metadata:
  name: store1-secrets
  namespace: store1
stringData:
  DATABASE_URL: "postgres://postgres:medusapass@store1-postgresql.store1.svc.cluster.local:5432/medusa?sslmode=require"
  REDIS_URL: "redis://default:medusaredispass@store1-redis-master.store1.svc.cluster.local:6379"
  MEDUSA_BACKEND_URL: "https://admin.store1.shopikool.store"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: "pk_test_1234567890"
  NEXT_PUBLIC_BASE_URL: "https://store1.shopikool.store"
  NEXT_PUBLIC_DEFAULT_REGION: "us"
  NEXT_PUBLIC_STRIPE_KEY: "pk_test_stripe_1234"
  REVALIDATE_SECRET: "supersecret"