apiVersion: apps/v1
kind: Deployment
metadata:
  name: store1-backend
  namespace: store1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store1-backend
  template:
    metadata:
      labels:
        app: store1-backend
    spec:
      containers:
        - name: backend
          image: davidkhan/medusadev:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: store1-backend-config
            - secretRef:
                name: store1-secrets